server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuanblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: 
    password: 
  redis:
      host: 
      port: 6379
  mail:
      host:  smtp.163.com
      username: 
      password: LTXVQGZWYVZKXKBB  #这里不是密码，是开启POP3/SMTP服务的密钥
      default-encoding: UTF-8

  rabbitmq:
    username: 
    password: 
    host: 127.0.0.1
    port: 5672

  data:
    elasticsearch:
        cluster-name: elasticsearch
       
        cluster-nodes: localhost:9300
        repositories:
            enabled: true
mail:
  fromMail:
    addr: 

mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

yuanblog:
    jwt:
      secret: 
      expire: 86400
      header: token